import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ channel: 'msedge', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:4173/practice');
  await page.getByRole('button', { name: '导入素材' }).click();
  await page.getByText('文章转语音 + 自动生成 SRT', { exact: true }).click();
  await page.getByLabel('文章名称', { exact: true }).fill('Article browser QA');
  await page.getByLabel('文章内容', { exact: true }).fill('Small steps make a big difference. Practice one sentence today.');
  await page.screenshot({ path: 'qa/article-import.png', fullPage: true });
  await page.getByRole('button', { name: '生成并导入练习' }).click();
  await page.waitForFunction(() => !document.querySelector('dialog[open]'), null, { timeout: 150000 });
  const lesson = await page.evaluate(async () => {
    const db = await new Promise((resolve, reject) => { const request = indexedDB.open('echo-shadowing', 1); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
    const lessons = await new Promise(resolve => { const request = db.transaction('lessons').objectStore('lessons').getAll(); request.onsuccess = () => resolve(request.result); });
    const lesson = lessons.find(item => item.title === 'Article browser QA');
    const audio = document.createElement('audio'); audio.src = URL.createObjectURL(lesson.media);
    const duration = await new Promise((resolve, reject) => { audio.onloadedmetadata = () => resolve(audio.duration); audio.onerror = reject; });
    URL.revokeObjectURL(audio.src); db.close();
    return { cues: lesson.segments, duration, srt: await lesson.subtitleFile.text(), article: await lesson.articleFile.text(), size: lesson.media.size };
  });
  assert.equal(lesson.cues.length, 2);
  assert.ok(Math.abs(lesson.duration - lesson.cues.at(-1).end) < 0.01);
  assert.ok(Math.abs(lesson.cues[1].start - lesson.cues[0].end - 0.25) < 0.001);
  assert.match(lesson.srt, /Small steps/); assert.match(lesson.article, /Practice one/);
  await page.getByRole('button', { name: '播放原声', exact: true }).click();
  await page.waitForFunction(() => [...document.querySelectorAll('audio')].some(audio => audio.currentTime > 0.3));
  await page.screenshot({ path: 'qa/article-generated.png', fullPage: true });
  await page.reload();
  await page.getByRole('button', { name: '导入素材' }).click();
  await page.getByRole('link', { name: '下载原文章' }).waitFor();
  await page.getByRole('link', { name: '下载原字幕' }).waitFor();
  await page.getByText('文章转语音 + 自动生成 SRT', { exact: true }).click();
  await page.getByLabel('文章内容', { exact: true }).fill('Cancellation test.');
  await page.route('**/api/tts', async route => { await new Promise(resolve => setTimeout(resolve, 1000)); await route.fulfill({ status: 502, contentType: 'application/json', body: '{"error":"test failure"}' }).catch(() => {}); });
  await page.getByRole('button', { name: '生成并导入练习' }).click();
  await page.getByRole('button', { name: '取消生成' }).click();
  await page.getByRole('button', { name: '生成并导入练习' }).waitFor();
  assert.equal(await page.getByLabel('文章内容', { exact: true }).inputValue(), 'Cancellation test.');
  await page.getByRole('button', { name: '生成并导入练习' }).click();
  await page.getByRole('alert').filter({ hasText: 'test failure' }).waitFor();
  assert.equal(await page.getByLabel('文章内容', { exact: true }).inputValue(), 'Cancellation test.');
  assert.deepEqual(errors, []);
  console.log('Article browser QA passed:', JSON.stringify(lesson));
} finally { await browser.close(); }
